[build]
  functions = "functions"  # A pasta onde as funções estão localizadas
  publish = ""  # Não há publicação de arquivos estáticos, se for só API

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200